### ISSUE TITLE
List virtual posters

### ISSUE THREAD

**Issue by ArtPoon** [ArtPoon/dynamics-evolution-indico#18]
We want to provide a way for virtual attendees to upload their poster as a PDF as well as a short video.  The Contributions List menu seems to be a natural way to do this - however, this will display *all* contributions (including talks and in-person posters).  In addition, this will display the abstract texts associated with the contributions (under the header Description).  

I think we can prevent this from happening by modifying the file `.venv/lib/python3.9/site-packages/indico/modules/events/contributions/templates/display/contribution_display.html` - specifially by commenting out this block:
```python
    {% if contribution.description %}
        <section>
            <div class="header">
                <div class="header-row">
                    <h3>{% trans %}Description{% endtrans %}</h3>
                </div>
            </div>
            <div class="description js-mathjax">
                {{ contribution.description }}
            </div>
        </section>
    {% endif %}
```

**Comment by ArtPoon** [comment]
We also need to restrict access to the uploaded materials to registered users

**Comment by stevenweaver** [comment]
Applied the following patch to version `3.2` of indico in `.venv/lib/python3.9/site-packages/indico/`

[remove_contribution_display.patch](https://github.com/ArtPoon/dynamics-evolution-indico/files/15313213/remove_contribution_display.patch)

**Comment by stevenweaver** [comment]
Updated patch to remove description from Contributor List view:

[remove_contribution_display.patch](https://github.com/ArtPoon/dynamics-evolution-indico/files/15313670/remove_contribution_display.patch)

**Comment by ArtPoon** [comment]
With @stevenweaver 's help we have a temporary fix for this.  We should replace this with template customization files as recommended by Indico documentation, but for the time being the above patches seem to be working.

**Comment by ArtPoon** [comment]
Next step is to configure current event page to display Contributions List
