### ISSUE TITLE
Need to set headers if using a reverse proxy with nginx

### ISSUE THREAD

**Issue by ArtPoon** [ArtPoon/dynamics-evolution-indico#20]
When the Indico instance was restarted, we were unable to access the webpages, with the site returning an error message: "This Indico instance can only be accessed via https://dynamicsevolution.org".  Page loads were logged under `/home/indico/log/indico.log` with the error message:
```
2024-05-14 16:14:01,147  INFO     9a7d98b9033b4fd0  1       indico.flask              Received request with invalid url root for http://dynamicsevolution.org/
```

@stevenweaver determined that the following lines needed to be added to the nginx config:
```sh
        proxy_set_header X-Real-IP  $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
        proxy_redirect off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
```

**Comment by stevenweaver** [comment]
Yes, specifically, this is when using a reverse proxy. The setting `proxy_set_header X-Forwarded-Proto $scheme;` was missing, which caused the issue.
